//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeutyWebModelFirst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container1 : DbContext
    {
        public Model1Container1()
            : base("name=Model1Container1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<Brand> BrandSet { get; set; }
        public virtual DbSet<Company> CompanySet { get; set; }
        public virtual DbSet<Manager> ManagerSet { get; set; }
        public virtual DbSet<Member> MemberSet { get; set; }
        public virtual DbSet<Bank> BankSet { get; set; }
        public virtual DbSet<Admin> AdminSet { get; set; }
        public virtual DbSet<Order> OrderSet { get; set; }
    }
}
